# Generated by Django 2.2.5 on 2019-09-10 17:43

import bson.objectid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('client_id', models.UUIDField(default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False, verbose_name='clientId')),
                ('firstname', models.TextField(max_length=50)),
                ('surname', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=120)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
