# Generated by Django 2.2.5 on 2019-09-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customers_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('client_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('term', models.IntegerField()),
                ('rate', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'db_table': 'loans',
            },
        ),
    ]
